/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillboardRouteImport } from './routes/billboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedIndexRouteImport } from './routes/saved/index'
import { Route as MarketLayoutRouteImport } from './routes/market/_layout'
import { Route as MarketLayoutTakaIndexRouteImport } from './routes/market/_layout/taka/index'
import { Route as MarketLayoutServicesIndexRouteImport } from './routes/market/_layout/services/index'
import { Route as MarketLayoutProductsIndexRouteImport } from './routes/market/_layout/products/index'
import { Route as MarketLayoutTakaIdRouteImport } from './routes/market/_layout/taka/$id'
import { Route as MarketLayoutServicesIdRouteImport } from './routes/market/_layout/services/$id'
import { Route as MarketLayoutProductsIdRouteImport } from './routes/market/_layout/products/$id'

const MarketRouteImport = createFileRoute('/market')()

const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardRoute = BillboardRouteImport.update({
  id: '/billboard',
  path: '/billboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketLayoutRoute = MarketLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => MarketRoute,
} as any)
const MarketLayoutTakaIndexRoute = MarketLayoutTakaIndexRouteImport.update({
  id: '/taka/',
  path: '/taka/',
  getParentRoute: () => MarketLayoutRoute,
} as any)
const MarketLayoutServicesIndexRoute =
  MarketLayoutServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => MarketLayoutRoute,
  } as any)
const MarketLayoutProductsIndexRoute =
  MarketLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => MarketLayoutRoute,
  } as any)
const MarketLayoutTakaIdRoute = MarketLayoutTakaIdRouteImport.update({
  id: '/taka/$id',
  path: '/taka/$id',
  getParentRoute: () => MarketLayoutRoute,
} as any)
const MarketLayoutServicesIdRoute = MarketLayoutServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => MarketLayoutRoute,
} as any)
const MarketLayoutProductsIdRoute = MarketLayoutProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => MarketLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/workshop': typeof WorkshopRoute
  '/market': typeof MarketLayoutRouteWithChildren
  '/saved': typeof SavedIndexRoute
  '/market/products/$id': typeof MarketLayoutProductsIdRoute
  '/market/services/$id': typeof MarketLayoutServicesIdRoute
  '/market/taka/$id': typeof MarketLayoutTakaIdRoute
  '/market/products': typeof MarketLayoutProductsIndexRoute
  '/market/services': typeof MarketLayoutServicesIndexRoute
  '/market/taka': typeof MarketLayoutTakaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/workshop': typeof WorkshopRoute
  '/market': typeof MarketLayoutRouteWithChildren
  '/saved': typeof SavedIndexRoute
  '/market/products/$id': typeof MarketLayoutProductsIdRoute
  '/market/services/$id': typeof MarketLayoutServicesIdRoute
  '/market/taka/$id': typeof MarketLayoutTakaIdRoute
  '/market/products': typeof MarketLayoutProductsIndexRoute
  '/market/services': typeof MarketLayoutServicesIndexRoute
  '/market/taka': typeof MarketLayoutTakaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/workshop': typeof WorkshopRoute
  '/market': typeof MarketRouteWithChildren
  '/market/_layout': typeof MarketLayoutRouteWithChildren
  '/saved/': typeof SavedIndexRoute
  '/market/_layout/products/$id': typeof MarketLayoutProductsIdRoute
  '/market/_layout/services/$id': typeof MarketLayoutServicesIdRoute
  '/market/_layout/taka/$id': typeof MarketLayoutTakaIdRoute
  '/market/_layout/products/': typeof MarketLayoutProductsIndexRoute
  '/market/_layout/services/': typeof MarketLayoutServicesIndexRoute
  '/market/_layout/taka/': typeof MarketLayoutTakaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billboard'
    | '/chat'
    | '/login'
    | '/profile'
    | '/signup'
    | '/workshop'
    | '/market'
    | '/saved'
    | '/market/products/$id'
    | '/market/services/$id'
    | '/market/taka/$id'
    | '/market/products'
    | '/market/services'
    | '/market/taka'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billboard'
    | '/chat'
    | '/login'
    | '/profile'
    | '/signup'
    | '/workshop'
    | '/market'
    | '/saved'
    | '/market/products/$id'
    | '/market/services/$id'
    | '/market/taka/$id'
    | '/market/products'
    | '/market/services'
    | '/market/taka'
  id:
    | '__root__'
    | '/'
    | '/billboard'
    | '/chat'
    | '/login'
    | '/profile'
    | '/signup'
    | '/workshop'
    | '/market'
    | '/market/_layout'
    | '/saved/'
    | '/market/_layout/products/$id'
    | '/market/_layout/services/$id'
    | '/market/_layout/taka/$id'
    | '/market/_layout/products/'
    | '/market/_layout/services/'
    | '/market/_layout/taka/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillboardRoute: typeof BillboardRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WorkshopRoute: typeof WorkshopRoute
  MarketRoute: typeof MarketRouteWithChildren
  SavedIndexRoute: typeof SavedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboard': {
      id: '/billboard'
      path: '/billboard'
      fullPath: '/billboard'
      preLoaderRoute: typeof BillboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/_layout': {
      id: '/market/_layout'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketLayoutRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/_layout/taka/': {
      id: '/market/_layout/taka/'
      path: '/taka'
      fullPath: '/market/taka'
      preLoaderRoute: typeof MarketLayoutTakaIndexRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
    '/market/_layout/services/': {
      id: '/market/_layout/services/'
      path: '/services'
      fullPath: '/market/services'
      preLoaderRoute: typeof MarketLayoutServicesIndexRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
    '/market/_layout/products/': {
      id: '/market/_layout/products/'
      path: '/products'
      fullPath: '/market/products'
      preLoaderRoute: typeof MarketLayoutProductsIndexRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
    '/market/_layout/taka/$id': {
      id: '/market/_layout/taka/$id'
      path: '/taka/$id'
      fullPath: '/market/taka/$id'
      preLoaderRoute: typeof MarketLayoutTakaIdRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
    '/market/_layout/services/$id': {
      id: '/market/_layout/services/$id'
      path: '/services/$id'
      fullPath: '/market/services/$id'
      preLoaderRoute: typeof MarketLayoutServicesIdRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
    '/market/_layout/products/$id': {
      id: '/market/_layout/products/$id'
      path: '/products/$id'
      fullPath: '/market/products/$id'
      preLoaderRoute: typeof MarketLayoutProductsIdRouteImport
      parentRoute: typeof MarketLayoutRoute
    }
  }
}

interface MarketLayoutRouteChildren {
  MarketLayoutProductsIdRoute: typeof MarketLayoutProductsIdRoute
  MarketLayoutServicesIdRoute: typeof MarketLayoutServicesIdRoute
  MarketLayoutTakaIdRoute: typeof MarketLayoutTakaIdRoute
  MarketLayoutProductsIndexRoute: typeof MarketLayoutProductsIndexRoute
  MarketLayoutServicesIndexRoute: typeof MarketLayoutServicesIndexRoute
  MarketLayoutTakaIndexRoute: typeof MarketLayoutTakaIndexRoute
}

const MarketLayoutRouteChildren: MarketLayoutRouteChildren = {
  MarketLayoutProductsIdRoute: MarketLayoutProductsIdRoute,
  MarketLayoutServicesIdRoute: MarketLayoutServicesIdRoute,
  MarketLayoutTakaIdRoute: MarketLayoutTakaIdRoute,
  MarketLayoutProductsIndexRoute: MarketLayoutProductsIndexRoute,
  MarketLayoutServicesIndexRoute: MarketLayoutServicesIndexRoute,
  MarketLayoutTakaIndexRoute: MarketLayoutTakaIndexRoute,
}

const MarketLayoutRouteWithChildren = MarketLayoutRoute._addFileChildren(
  MarketLayoutRouteChildren,
)

interface MarketRouteChildren {
  MarketLayoutRoute: typeof MarketLayoutRouteWithChildren
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketLayoutRoute: MarketLayoutRouteWithChildren,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillboardRoute: BillboardRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WorkshopRoute: WorkshopRoute,
  MarketRoute: MarketRouteWithChildren,
  SavedIndexRoute: SavedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
